class ConfigJogo:
    ALTURA_TELA = 400
    LARGURA_TELA = 600
    ALTURA_TELA_PRINCIPAL = 700
    LARGURA_TELA_PRINCIPAL = 1050
    COR_TITULO = (255, 0, 0)
    COR_TEXTO = (0, 0, 0)
    COR_CAIXA = (0, 0, 0)
    COR_SELECTION = (255, 0, 0)
    FONTE_TITULO = 72
    FONTE_SUBTITULO = 36
    FONTE_HISTORIA = 24
    TELA = 0
    VELOCIDADE_P = 1
    ALTURA_P = (0.11 * ALTURA_TELA_PRINCIPAL)
    LARGURA_P = (0.05 * LARGURA_TELA_PRINCIPAL)
    POS_X1 = (0.1 * LARGURA_TELA_PRINCIPAL)
    POS_X2 = (0.9 * LARGURA_TELA_PRINCIPAL - LARGURA_P)

